# Generated by Django 4.2.1 on 2023-07-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablog', '0002_blogcontain_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontain',
            name='author',
        ),
    ]
